### ISSUE TITLE
Missing 'Ornn' as the required Ally/required_ally

### ISSUE THREAD

**Issue by ViniciusNascDeMoraes** [meraki-analytics/lolstaticdata#69] opened 2023-08-19 12:45 UTC
Some items in the list are Ornn Upgrades and are missing 'Ornn' as the required Ally/required_ally. Here is the items:

- Equinox
- Infinite Convergence
- Primordial Dawn

**Comment by bangingheads** [comment] 2023-12-09 00:32
This is caused by Riot's data in the client being inaccurate. We could potentially add an override for these cases.

**Comment by jjmaldonis** [comment] 2024-04-10 05:13
Infinite Convergence has Ornn as a required ally so it looks like this is fixed. Closing this issue.

**Closed by jjmaldonis** 2024-04-10 05:13 UTC
